### ISSUE TITLE
Fix external models folder (like a1111) cannot be detected by Model manager

### ISSUE THREAD

**Issue by Weixuanf** [11cafe/Internal_Roadmap#3]
When installing model, if user shares model folder with a111, it cannot detect and will still install into comfyui path.

Will model list drawer also fail to display installed models if user share model path with a111?  Can you check @arslan2012 

![image](https://github.com/11cafe/Internal_Roadmap/assets/18367033/d20b380e-557c-4beb-be58-e03a3afd8cb8)

**Comment by arslan2012** [comment]
> Will model list drawer also fail to display installed models if user share model path with a111?

No it won't, the display is fine, only the download directory needs to be changed

**Comment by Weixuanf** [comment]
So it means that if I share model folder with a111, the model list can display fine, but installing model won’t go to a111 model folder, instead it goes to comfyui folder?
________________________________

**Comment by arslan2012** [comment]
yes, exactly, that why I've been using it just fine.

**Comment by Weixuanf** [comment]
Ok, then let’s just fix the installation path to detect external model folder. Thanks!!
________________________________

**Comment by arslan2012** [comment]
Closed by https://github.com/11cafe/comfyui-workspace-manager/commit/57e51bf5b106c3d32fc13cf5cf2df47bbc89ff53
